# Generated by Django 6.0.2 on 2026-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('chat_title', models.CharField(blank=True, default='', max_length=255)),
                ('project_status', models.CharField(default='Active', max_length=50)),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('share_with', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
