# Generated by Django 6.0.2 on 2026-02-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
