# Generated by Django 6.0.2 on 2026-02-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('estate_type', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(blank=True, default='Available', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enquiry', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Fresh Lead', 'Fresh Lead'), ('Returning', 'Returning'), ('Untouched', 'Untouched'), ('Unassigned', 'Unassigned'), ('Assigned', 'Assigned')], default='Fresh Lead', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('Sale', 'Sale'), ('Lease', 'Lease'), ('Other', 'Other')], default='Sale', max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='dashboard.lead')),
            ],
            options={
                'ordering': ['-visit_date', '-id'],
            },
        ),
    ]
