from django.urls import path, re_path
from django.views.generic import RedirectView

from . import views


urlpatterns = [
    path("", views.login, name="login"),
    path("login/", views.login, name="login-page"),
    path("index/", views.index, name="index"),
    path("dashboard", views.index, name="dashboard-no-slash"),
    path("dashboard/", views.index, name="dashboard"),
    path("crmhome/", views.crm_home, name="crmhome"),
    path("lead/", views.lead, name="lead"),
    path("listings/", views.listings, name="listings"),
    path("library/", views.library, name="library"),
    path("contact/", views.contact, name="contact"),
    path("deals/", views.deals, name="deals"),
    path("estate/", views.estate, name="estate"),
    path("add-task/", views.add_task, name="add-task"),
    path("complete-task/", views.complete_task, name="complete-task"),
    path("task-list/", views.task_list, name="task-list"),
    path("add-project/", views.add_project, name="add-project"),
    path("agent/", views.agent, name="agent"),
    path("company/", views.company, name="company"),
    path("api/staff-users", views.staff_users_api, name="api-staff-users"),
    path("login.html", RedirectView.as_view(pattern_name="login", permanent=False)),
    path("index.html", RedirectView.as_view(pattern_name="index", permanent=False)),
    path("crmhome.html", RedirectView.as_view(pattern_name="crmhome", permanent=False)),
    path("Lead.html", RedirectView.as_view(pattern_name="lead", permanent=False)),
    path("lead.html", RedirectView.as_view(pattern_name="lead", permanent=False)),
    path("leads.html", RedirectView.as_view(pattern_name="lead", permanent=False)),
    path("Listings.html", RedirectView.as_view(pattern_name="listings", permanent=False)),
    path("listings.html", RedirectView.as_view(pattern_name="listings", permanent=False)),
    path("Library.html", RedirectView.as_view(pattern_name="library", permanent=False)),
    path("contact.html", RedirectView.as_view(pattern_name="contact", permanent=False)),
    path("deals.html", RedirectView.as_view(pattern_name="deals", permanent=False)),
    path("estate.html", RedirectView.as_view(pattern_name="estate", permanent=False)),
    path("AddTask.html", RedirectView.as_view(pattern_name="add-task", permanent=False)),
    path("completeTask.html", RedirectView.as_view(pattern_name="complete-task", permanent=False)),
    path("Addproject.html", RedirectView.as_view(pattern_name="add-project", permanent=False)),
    path("Agent.html", RedirectView.as_view(pattern_name="agent", permanent=False)),
    path("Company.html", RedirectView.as_view(pattern_name="company", permanent=False)),
    path("CRM.html", RedirectView.as_view(pattern_name="crmhome", permanent=False)),
    path("TaskList.html", RedirectView.as_view(pattern_name="task-list", permanent=False)),
    path("Tasklist.html", RedirectView.as_view(pattern_name="task-list", permanent=False)),
    path("project.html", RedirectView.as_view(pattern_name="add-project", permanent=False)),
    path("professional.html", RedirectView.as_view(pattern_name="agent", permanent=False)),
    path("Marketing.html", RedirectView.as_view(pattern_name="marketing", permanent=False)),
    path("report.html", RedirectView.as_view(pattern_name="index", permanent=False)),
    path("Report.html", RedirectView.as_view(pattern_name="index", permanent=False)),
    path("dashboard.html", RedirectView.as_view(pattern_name="dashboard", permanent=False)),
    re_path(r"^(?P<folder>css|images)/(?P<asset_path>.+)$", views.legacy_asset),
    re_path(r"^[^/]+/(?P<folder>css|images)/(?P<asset_path>.+)$", views.legacy_asset),
    re_path(r"^[^/]+/static/(?P<asset_path>.+)$", views.legacy_static),
    re_path(r"^(?P<asset_name>[^/]+\.(?:png|jpg|jpeg|gif|webp|svg))$", views.legacy_image_root),
]


